### PR TITLE
Update landmarker.io to ts_react

### PR DESCRIPTION
**Pull request by gabrielcowley**
The primary aim of this PR is mainly to update the `landmarker.io` submodule to the `ts_react` branch (done) and handle all necessary changes that go along with that. The following objectives are also addressed in this PR:

Update the build system (partially done).
Bump to the latest Electron version (done) and handle any API changes (partially done).
Packaging for Windows, Linux and macOS (not yet started).

### CODE REVIEW

**Comment by jabooth** [comment]
@gabrielcowley awesome!

It's obviously a grim diff, but looking through it all seems very sensible. Nice!

No one is currently working of master for landmarker-app, so if you feel this is at even a rough working state let's get this merged so we can do smaller PRs going forwards for:

- final API changes
- packaging for Windows, Linux and macOS

Just let me know if you think that's OK and I'll go ahead and merge.

**Comment by gabrielcowley** [comment]
@jabooth It starts up okay, but after you select an asset folder, it crashes. I'm working on it now, but maybe hold off on the merge. I'll let you know as soon as it's usable.

**Comment by gabrielcowley** [comment]
@jabooth The application is now vaguely usable - there are problems with 'logging out' of the current mode and the fonts don't currently load so there are a load of weird symbols all over the place. If that's good enough for you then you can merge if you like.

**Comment by gabrielcowley** [comment]
I think the tool is now functioning as well as the `ts_react` branch on [landmarker.io](https://github.com/menpo/landmarker.io/tree/ts_react).

The only exception is that the 'save' and 'download' menu options are disconnected from the `landmarker.io` code because the new React components which constitute the 'save' and 'download' buttons can no longer be selected through `$('#save')` and `$('#download')` respectively. This can be easily fixed by re-adding the `id` property to these buttons.

**Comment by jabooth** [comment]
OK @gabrielcowley sounds great, let's get this merged if you are fairly happy and then work on smaller PR's from this base.

Nice!

**Pull request merged**
