### PR TITLE
Add 'auto-update' functionality

### PR DESCRIPTION
**Pull request by gabrielcowley**
`electron-builder` packaging and publishing has already been added to this project, but this PR adds the capability for auto-updating from the app itself or just checking for updates on Linux (which does not support auto-updating). The app checks for updates when a backend has been started up from the Intro modal and when the user clicks 'Check for updates' in the Menu bar.

### CODE REVIEW

**Comment by gabrielcowley** [comment]
It seems that putting an encrypted GH_TOKEN in `appveyor.yml` does not work - we need to submit the GitHub access token as an environment variable in the AppVeyor settings instead (and remember to enable encryption).

**Comment by patricksnape** [comment]
An access token for who? If you give me it I can add it to Appveyor.

**Comment by gabrielcowley** [comment]
@patricksnape A GitHub personal access token of any member of Menpo should do

**Comment by patricksnape** [comment]
Sorry, I'm a bit out of the loop here - what exactly would the token be used for? Because i'm worried that if I give it my access token then it would access to many menpo repos and then someone could push PRs that control menpo.

**Comment by gabrielcowley** [comment]
@patricksnape The access token allows `electron-builder` to upload installer packages to a GitHub draft release through the GitHub API. This appears to be working on Travis but not on AppVeyor. I now suspect that the problem isn't the fact that the environment variable is in the `.yml` file in encrypted form rather than in the AppVeyor settings, because I set up an AppVeyor build for my forked repo and it worked fine. I think the problem is that I'm don't have sufficient AppVeyor permissions (the project does not appear on my AppVeyor 'Projects' page).

So I think the solution is either to grant me the necessary permissions or for an owner/admin of the AppVeyor project to encrypt their access token and replace the existing `GH_TOKEN` variable in the `.yml` file. Hope that all makes sense.

**Comment by patricksnape** [comment]
It's weird, you are an admin of the Landmarker group and a set up as a collaborator. Nevertheless, I committed my encrypted token personal access token for repo access

**Comment by patricksnape** [comment]
Quoting from [here](http://help.appveyor.com/discussions/questions/2615-secure-variables-for-pull-request)
> Hi Joel,
> 
> By default secure variables are not exposed on PRs, so you are safe. If you want you can set "Enable secure variables in Pull Requests from the same repository only" to allow trusted contributors to use them.
> 
> --ilya.

So the issue is actually that this is a PR from your fork and Appveyor literally doesn't expose the encrypted variable. So, in order to make this work - you need to close this PR and re-open it as a branch directly on the landmarker-app and then re-open the PR. This should then work.

**Comment by patricksnape** [comment]
I closed this as discussed above and re-opened #9

**Pull request closed without merging**
